# Generated by Django 5.2.6 on 2025-09-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_activated_password',
            field=models.BooleanField(default=False),
        ),
    ]
