# Generated by Django 5.2.6 on 2025-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
