# Generated by Django 5.2.6 on 2025-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tenants/attachments/'),
        ),
    ]
