services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django_app
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - django

  db:
    image: postgres:15
    container_name: postgres_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
