# Generated by Django 5.2.6 on 2025-09-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_price', '0002_alter_propertyprice_options_propertyprice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyprice',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
