# Generated by Django 5.2.6 on 2025-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_price', '0003_alter_propertyprice_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyprice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyprice',
            name='start_date',
            field=models.DateField(),
        ),
    ]
