# Generated by Django 5.2.6 on 2025-09-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_alter_block_code_alter_block_name'),
        ('property', '0002_alter_property_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('property_no', 'name', 'block')},
        ),
    ]
